var keyMirror = require('key-mirror');

// Define action constants
module.exports = keyMirror({
	CHANGE_IS_TEST_FILTER: null,
	SHOW_ANNOUNCEMENT_MODAL: null,
	CLOSE_ANNOUNCEMENT_MODAL: null,

	GET_DEPARTMENTS_ATTEMPT: null,
	GET_DEPARTMENTS_SUCCESS: null,

	GET_CLIENT_APPS_ATTEMPT: null,
	GET_CLIENT_APPS_SUCCESS: null,
	GET_CLIENT_APP_CATEGORIES_ATTEMPT: null,
	GET_CLIENT_APP_CATEGORIES_SUCCESS: null,
	GET_CLIENT_APP_ALL_CATEGORIES_ATTEMPT: null,
	GET_CLIENT_APP_ALL_CATEGORIES_SUCCESS: null,
	GET_CLIENT_APP_SUBCATEGORIES: null,

	GET_IMPROVEMENT_CATEGORIES_ATTEMPT: null,
	GET_IMPROVEMENT_CATEGORIES_SUCCESS: null,
	SET_VALUE_OF_IMPROVEMENT: null,
	CREATE_IMPROVEMENT_ATTEMPT: null,
	CREATE_IMPROVEMENT_SUCCESS: null,
	SET_IMPROVEMENT_LIST_FILTER: null,
	LOAD_IMPROVEMENT_LIST_ATTEMPT: null,
	LOAD_IMPROVEMENT_LIST_SUCCESS: null,
	LOAD_ALL_ESSAYCOCK_USERS_ATTEMPT: null,
	LOAD_ALL_ESSAYCOCK_USERS_SUCCESS: null,
	RESET_IMPROVEMENT_LIST_FILTERS: null,
	CREATE_VERIFICATION_REQUEST_ATTEMPT: null,
	VERIFICATION_REQUEST_SAVED: null,
	UPDATE_VERIFICATION_REQUEST: null,
	SEND_DOCUMENTS: null,
	VERIFICATION_FILES_UPLOADED: null,

	SHOW_INFO_ABOUT_SELECTED_CATEGORY: null,
	SET_CURRENT_CLIENT_APP: null,
	SET_CURRENT_CATEGORY: null,
	SET_CURRENT_SUBCATEGORY: null,
	GET_CATEGORY_INFO_ATTEMPT: null,
	GET_CATEGORY_INFO_SUCCESS: null,
	APPLY_CATEGORY_CHANGES_ATTEMPT: null,
	APPLY_CATEGORY_CHANGES_SUCCESS: null,
	DELETE_CATEGORY_ATTEMPT: null,
	DELETE_CATEGORY_SUCCESS: null,
	SHOW_ADDING_NEW_CATEGORY_FORM: null,
	HIDE_ADDING_NEW_CATEGORY_FORM: null,
	ADD_NEW_CATEGORY_ATTEMPT: null,
	ADD_NEW_CATEGORY_SUCCESS: null,
	SET_FILTERS_FOR_POSTS: null,
	EDIT_SELECTED_BLOGPOST: null,
	CANCEL_EDIT_SELECTED_BLOGPOST: null,
	DELETE_SELECTED_BLOGPOST_ATTEMPT: null,
	DELETE_SELECTED_BLOGPOST_SUCCESS: null,
	ADD_NEW_BLOGPOST_ATTEMPT: null,
	ADD_NEW_BLOGPOST_SUCCESS: null,
	CHANGE_BLOGPOST_CATEGORY_ID: null,
	SHOW_ADDING_NEW_POST_FORM: null,
	HIDE_ADDING_NEW_POST_FORM: null,
	GET_POSTS_FOR_TABLE_ATTEMPT: null,
	GET_POSTS_FOR_TABLE_SUCCESS: null,
	CHANGE_BLOGPOST_APP_ID: null,
	GET_POST_INFO_ATTEMPT: null,
	GET_POST_INFO_SUCCESS: null,
	GET_ALL_CATS_ATTEMPT: null,
	GET_ALL_CATS_SUCCESS: null,
	CONFIRM_POST_EDIT_ATTEMPT: null,
	CONFIRM_POST_EDIT_SUCCESS: null,
	DELETE_BLOGPOST_TAG_SUCCESS: null,

	GET_ALL_RA_FILTERS_ATTEMPT: null,
	GET_ALL_RA_FILTERS_SUCCESS: null,
	REVIEW_ACTION_FILTER_CHANGED: null,
	CHANGE_DATE_IN_FILTER: null,

	CHANGE_FILE_VISIBILITY_ATTEMPT: null,
	CHANGE_FILE_VISIBILITY_SUCCESS: null,

	LOAD_TOP_WMS_ATTEMPT: null,
	LOAD_TOP_WMS_SUCCESS: null,

	GET_MARKS_ATTEMPT: null,
	GET_MARKS_SUCCESS: null,

	CHANGE_PAGE: null,

	CHANGE_ROWS_COLOR_PREFERENCE: null,
	CHANGE_WRITER_LIST_LOAD_PREFERENCES: null,

	SEND_FILE_FOR_PLAG_CHECK_ATTEMPED: null,
	SEND_FILE_FOR_PLAG_CHECK_SUCCESS: null,

	COMMON_STATE_CHANGE: null,
	PAPER_DETAILS_CHANGE: null,
	EXACT_DEADLINE_CHANGE: null,
	USER_STATE_CHANGE: null,
	ACADEMIC_LEVEL_CHANGE: null,
	PAPER_TYPE_CHANGE: null,
	WORK_TYPE_CHANGE: null,
	DEADLINE_CHANGE: null,
	PAGES_CHANGE: null,
	SPACING_CHANGE: null,
	SLIDES_CHNAGE: null,
	PASSWORD_SHOWN_CHANGE: null,
	PROBLEMS_CHANGE: null,
	EXISTING_USER_CHANGE: null,
	WILL_SHOW_CALCULATOR: null,
	RECEIVE_DATA: null,
	USER_LIST_LOADED: null,

	SET_UPSALE: null,
	APPLY_UPSALE: null,

	INQUIRY_CREATE_ATTEMPT: null,
	INQUIRY_CREATE_SUCCESS: null,

	SIGN_IN_SUCCESS: null,
	SIGN_IN_ATTEMPT: null,
	SIGN_UP: null,
	SIGN_UP_IN_ERROR: null,
	SIGN_UP_IN_ALERT: null,
	UPDATE_USER_ATTEMPT: null,
	UPDATE_USER_SUCCESS: null,
	FORGOT_PASSWORD_ATTEMPT: null,
	RESET_PASSWORD_ATTEMPT: null,
	LOG_OUT: null,

	CHANGE_PASSWORD_ATTEMPT: null,
	CHANGE_PASSWORD_SUCCESS: null,

	STOP_CHECKING_ORDER_PAYMENT: null,
	ORDER_PAY_ATTEMPT: null,
	ORDER_CREATE_ATTEMPT: null,
	ORDER_CREATE_SUCCESS: null,
	ORDER_UPDATE: null,
	ORDER_UPDATE_SUCCESS: null,
	ORDER_DELETE: null,
	ORDERS_LOADED: null,
	ORDERS_LOAD_ATTEMPT: null,
	ORDERS_DELIVER_ATTEMPT: null,
	ORDER_TOGGLE_TRACKING: null,

	NOTIFICATIONS_LOAD_ATTEMPT:null,
	NOTIFICATIONS_LOADED:null,
	NOTIFICATION_FORCE_REFRESH:null,
	NOTIFICATION_LOAD_SUCCESS:null,
	ADD_FILTER_NOTIFICATION:null,
	UPDATE_FILTER_NOTIFICATION:null,
	REMOVE_FILTER_NOTIFICATION:null,
	FULL_TEXT_SEARCH_NOTIFICATION:null,
	NOTIFICATION_SEARCH_SUCCESS:null,

	TOGGLE_MENU: null,
	HASH_CHANGE: null,

	ADD_FILES: null,
	REMOVE_FILE: null,
	REMOVE_UPLOADED_FILE: null,
	UPLOAD_FILES: null,
	FILES_UPLOAD_SUCCESS: null,

	ADD_FILTER: null,
	SET_FILTERS: null,
	UPDATE_FILTER: null,
	REMOVE_FILTER: null,
	RESET_FILTERS: null,
	UPDATE_SORTING: null,
	// SET_MY_ORDERS: null,
	ORDER_FORCE_REFRESH: null,
	DISMISS_ALERTS: null,

	LOAD_STATS_ATTEMPT: null,
	LOAD_STATS_SUCCESS: null,

	LOAD_DAILY_STATS_ATTEMPT: null,
	LOAD_DAILY_STATS_SUCCESS: null,

	LOAD_DETAILED_DAILY_STATS_ATTEMPT: null,
	LOAD_DETAILED_DAILY_STATS_SUCCESS: null,

	UNREAD_MESSAGES_LOAD_ATTEMPT: null,
	UNREAD_MESSAGES_LOAD_SUCCESS: null,

	SUPPORT_MESSAGES_LOAD_ATTEMPT: null,
	SUPPORT_MESSAGES_LOAD_SUCCESS: null,

	MESSAGES_LOADED: null,
	MESSAGE_ATTEMPT: null,
	MESSAGE_SENT: null,
	MESSAGE_DELETE: null,
	MESSAGE_READ_ATTEMPT: null,
	MESSAGE_READ_SUCCESS: null,

	NOTE_ADD_ATTEMPT: null,
	NOTE_ADD_SUCCESS: null,
	NOTE_DELETE: null,

	REMINDER_LIST_UPDATE: null,
	REMINDER_ADD_ATTEMPT: null,
	REMINDER_UPDATE_ATTEMPT: null,
	REMINDER_DELETE_ATTEMPT: null,
	REMINDER_ADD_SUCCESS: null,
	REMINDER_LIST_LOAD_ATTEMPT: null,
	REMINDER_LIST_LOAD_SUCCESS: null,

	DISCOUNT_VERIFY_ATTEMPT: null,
	DISCOUNT_VERIFY_SUCCESS: null,
	DISCOUNT_VERIFY_ERROR: null,
	DISCOUNT_CODE_CHANGE: null,

	LOAD_CLIENT_ACTIONS_ATTEMPT: null,
	LOAD_CLIENT_ACTIONS_SUCCESS: null,

	LOAD_CLIENT_DETAILS_ATTEMPT: null,
	CLIENT_DETAILS_LOADED: null,

	PRICE_GROUP_LIST_LOADED: null,

	ASSIGNMENT_FROM_ORDER: null,
	ASSIGNMENT_CHANGE: null,
	ASSIGNMENT_ADD_PRICE_GROUP: null,
	ASSIGNMENT_CREATE_ATTEMPT: null,
	ASSIGNMENT_UPDATE_ATTEMPT: null,
	ASSIGNMENT_LOAD_ATTEMPT: null,
	ASSIGNMENT_LOAD_SUCCESS: null,
	ASSIGNMENT_LOAD_FAIL: null,
	ASSIGNMENT_CREATE_SUCCESS: null,
	ASSIGNMENT_EMAIL_ATTEMPT: null,
	ASSIGNMENT_LIST_MARK: null,
	ASSIGNMENT_CHANGE_SUCCESS: null,

	ASSIGN_WRITER: null,
	CONFIRM_WRITER: null,
	WRITER_CONFIRM_SUCCESS: null,
	LOAD_WRITER_DETAILS: null,
	WRITERS_ACTIVATED_LIST_LOADED: null,
	WRITER_LIST_LOADED: null,
	WRITER_DETAILS_LOADED: null,
	WRITER_MATCHING_IP_LIST_LOADED: null,
	WRITER_MATCHING_IP_SINGLE_LIST_LOADED: null,

	MATCHING_IP_LIST_LOAD_ATTEMPT: null,

	GET_ACTIVATED_WRITERS_ATTEMPT: null,
	ADD_WRITERS_ATTEMPT: null,
	ADD_WRITERS_SUCCESS: null,
	SET_AUTO_ASSIGNED: null,
	DELETE_WRITER_SUCCESS: null,

	LOAD_SUPPORT_DETAILS: null,
	SUPPORT_LIST_LOADED: null,
	SUPPORT_DETAILS_LOADED: null,

	WEBMASTER_LIST_LOAD_ATTEMPT: null,
	WEBMASTER_LIST_LOAD_SUCCESS: null,

	CREATE_TRANSACTION_ATTEMPT: null,
	CREATE_TRANSACTION_SUCCESS: null,
	CREATE_FINE_SUCCESS: null,






	URL_TRANSITION_SUCCESS: null,

	PRICE_GROUP_LIST_ATTEMPT: null,
	LOAD_CLIENT_LIST_ATTEMPT: null,

	ORDER_LOAD_SUCCESS: null,
	GIVE_USER_TO_WM_ATTEMPT: null,
	DISABLE_LOADING_STATE: null,
	BOOTSTRAP_ATTEMPT: null,
	BOOTSTRAP_SUCCESS: null,

	CREATE_SHIFT_ATTEMPT: null,
	CREATE_SHIFT_SUCCESS: null,

	CREATE_SHIFT_FROM_TEMPLATE_ATTEMPT: null,
	CREATE_SHIFT_FROM_TEMPLATE_SUCCESS: null,

	GET_SHIFT_LIST_ATTEMPT: null,
	GET_SHIFT_LIST_SUCCESS: null,

	GET_SALES_STATS_ATTEMPT: null,
	GET_SALES_STATS_SUCCESS: null,

	UPDATE_SHIFT_ATTEMPT: null,
	UPDATE_SHIFT_SUCCESS: null,

	GET_CURRENT_SHIFT_ATTEMPT: null,
	GET_CURRENT_SHIFT_SUCCESS: null,

	START_SHIFT_ATTEMPT: null,
	START_SHIFT_SUCCESS: null,

	DELETE_SHIFT_ATTEMPT: null,
	DELETE_SHIFT_SUCCESS: null,

	ADD_SHIFT_TO_LIST_ATTEMPT: null,

	LOAD_SUPPORTS_HOURS_ATTEMPT: null,
	LOAD_SUPPORTS_HOURS_SUCCESS: null,

	GET_SUPPORT_TRANSACTION_LIST_ATTEMPT: null,
	GET_SUPPORT_TRANSACTION_LIST_SUCCESS: null,

	REQUEST_BONUS_ATTEMPT: null,
	REQUEST_BONUS_SUCCESS: null,

	GET_SUPPORT_BONUS_REQUEST_LIST_ATTEMPT: null,
	GET_SUPPORT_BONUS_REQUEST_LIST_SUCCESS: null,

	GET_BONUS_REQUEST_LIST_ATTEMPT: null,
	GET_BONUS_REQUEST_LIST_SUCCESS: null,

	UPDATE_BONUS_REQUEST_ATTEMPT: null,
	UPDATE_BONUS_REQUEST_SUCCESS: null,

	DELETE_BONUS_REQUEST_ATTEMPT: null,
	DELETE_BONUS_REQUEST_SUCCESS: null,

	ACTIVATE_WRITER_ATTEMPT: null,
	ACTIVATE_WRITER_SUCCESS: null,

	DROP_ESSAY_ATTEMPT: null,
	DROP_ESSAY_SUCCESS: null,

	SAVE_PRICE_GROUP_ATTEMPT: null,
	SAVE_PRICE_GROUP_SUCCESS: null,

	LOAD_ANNOUNCEMENT_LIST_ATTEMPT: null,
	ANNOUNCEMENT_LIST_LOADED: null,

	LOAD_ANNOUNCEMENT_DETAILS_ATTEMPT: null,
	LOAD_ANNOUNCEMENT_DETAILS_SUCCESS: null,

	UPDATE_ANNOUNCEMENT_ATTEMPT: null,
	UPDATE_ANNOUNCEMENT_SUCCESS: null,

	CREATE_ANNOUNCEMENT_ATTEMPT: null,
	CREATE_ANNOUNCEMENT_SUCCESS: null,

	LOAD_ANNOUNCEMENTS_ATTEMPT: null,
	LOAD_ANNOUNCEMENTS_SUCCESS: null,

	MARK_ANNOUNCEMENTS_AS_READ_ATTEMPT: null,
	MARK_ANNOUNCEMENTS_AS_READ_SUCCESS: null,

	REMOVE_ANNOUNCEMENT_ATTEMPT: null,
	REMOVE_ANNOUNCEMENT_SUCCESS: null,

	CHECK_PURSE_ATTEMPT: null,
	CHECK_PURSE_SUCCESS: null,

	CREATE_REVISION_ATTEMPT: null,
	CREATE_REVISION_SUCCESS: null,
	UPDATE_REVISION_ATTEMPT: null,
	UPDATE_REVISION_SUCCESS: null,

	CREATE_ADD_PAYMENT_ATTEMPT: null,
	CREATE_ADD_PAYMENT_SUCCESS: null,
	UPDATE_ADD_PAYMENT_ATTEMPT: null,
	UPDATE_ADD_PAYMENT_SUCCESS: null,
	DELETE_ADD_PAYMENT_ATTEMPT: null,
	DELETE_ADD_PAYMENT_SUCCESS: null,

	GET_REVIEW_LIST_ATTEMPT: null,
	GET_REVIEW_LIST_SUCCESS: null,

	// GET_REVIEW_CATEGORY_LIST_ATTEMPT: null,
	// GET_REVIEW_CATEGORY_LIST_SUCCESS: null,

	GET_USER_REVIEW_LIST_ATTEMPT: null,

	GET_ORDER_REVIEW_LIST_ATTEMPT: null,
	GET_ORDER_REVIEW_LIST_SUCCESS: null,

	GET_NOTIFICATION_REVIEW_LIST_ATTEMPT: null,
	GET_NOTIFICATION_REVIEW_LIST_SUCCESS: null,

	GET_ORDER_REVIEW_ATTEMPT: null,
	GET_ORDER_REVIEW_SUCCESS: null,

	CREATE_ORDER_REVIEW_ATTEMPT: null,
	CREATE_ORDER_REVIEW_SUCCESS: null,

	GET_DISCOUNT_LIST_ATTEMPT: null,
	GET_DISCOUNT_LIST_SUCCESS: null,
	CREATE_DISCOUNT_LIST_ATTEMPT: null,
	CREATE_DISCOUNT_LIST_SUCCESS: null,

	GET_DISCOUNT_TYPES_ATTEMPT: null,
	GET_DISCOUNT_TYPES_SUCCESS: null,
	CREATE_DISCOUNT_TYPES_ATTEMPT: null,
	CREATE_DISCOUNT_TYPES_SUCCESS: null,

	CREATE_WQC_ATTEMPT: null,
	CREATE_WQC_SUCCESS: null,
	UPDATE_WQC_ATTEMPT: null,
	UPDATE_WQC_SUCCESS: null,
	DELETE_WQC_ATTEMPT: null,
	DELETE_WQC_SUCCESS: null,
	// GET_WQC_LIST_ATTEMPT: null,
	// GET_WQC_LIST_SUCCESS: null,

	UPDATE_DISCOUNT_ATTEMPT : null,
	UPDATE_DISCOUNT_SUCCESS : null,

	UPDATE_DISCOUNT_TYPE_ATTEMPT : null,
	UPDATE_DISCOUNT_TYPE_SUCCESS : null,

	GET_TRANSACTION_LIST_ATTEMPT : null,
	GET_TRANSACTION_LIST_SUCCESS : null,

	ADD_FILTER_TRANSACTION : null,
	UPDATE_FILTER_TRANSACTION : null,
	REMOVE_FILTER_TRANSACTION : null,

	UPDATE_PRESETS : null,
	REMOVE_PRESETS : null,

	UPDATE_REVIEW_STATUS_ATTEMPT: null,
	UPDATE_REVIEW_STATUS_SUCCESS: null,

	GET_USER_REVIEW_LIST_SUCCESS: null,
	GET_ORDER_REVIEW_LIST_SUCCESS: null,

	GET_UNPROCESSED_CALLBACK_LIST_ATTEMPT: null,
	GET_UNPROCESSED_CALLBACK_LIST_SUCCESS: null,

	UPDATE_CALLBACK_ATTEMPT: null,
	UPDATE_CALLBACK_SUCCESS: null,

	GET_PROCESSED_CALLBACK_LIST_ATTEMPT: null,
	GET_PROCESSED_CALLBACK_LIST_SUCCESS: null,

	WRITER_LIST_ATTEMPT: null,
	WRITER_LIST_SUCCESS: null,

	ADD_FILTER_FOR_WRITER: null,
	UPDATE_FILTER_FOR_WRITER: null,
	REMOVE_FILTER_FOR_WRITER: null,

	ADD_FILTER_FOR_CLIENT: null,
	UPDATE_FILTER_FOR_CLIENT: null,
	REMOVE_FILTER_FOR_CLIENT: null,

	WRITER_FILTERS_C_AND_A:null,
	WRITER_FILTERS_CLEAR:null,

	CLIENT_FILTERS_C_AND_A:null,
	CLIENT_FILTERS_CLEAR:null,

	DELETE_TRANSACTION_ATTEMPT:null,
	DELETE_TRANSACTION_SUCCESS:null,
	RESTORE_TRANSACTION_ATTEMPT:null,

	/*tveng*/
	WEBMASTER_CUT_LIST_LOAD_ATTEMPT: null,
	WEBMASTER_CUT_LIST_LOAD_SUCCESS: null,

	GET_KPI_ATTEMPT: null,
	GET_KPI_SUCCESS: null,

	REVIEW_FILTER_CHANGED: null,

	HIDE_MANAGE_REVIEW_MODAL: null,
	SHOW_MANAGE_REVIEW_MODAL: null,

	GET_CLIENT_GRUDGE_LIST_ATTEMPT: null,
	GET_CLIENT_GRUDGE_LIST_SUCCESS: null,

	GET_REVIEW_ACTION_TYPE_LIST_ATTEMPT: null,
	GET_REVIEW_ACTION_TYPE_LIST_SUCCESS: null,

	CREATE_REVIEW_ACTION_ATTEMPT: null,
	CREATE_REVIEW_ACTION_SUCCESS: null,

	UPDATE_REVIEW_ACTION_ATTEMPT: null,
	UPDATE_REVIEW_ACTION_SUCCESS: null,

	GET_REVIEW_ACTION_LIST_ATTEMPT: null,
	GET_REVIEW_ACTION_LIST_SUCCESS: null,

	GET_ORDER_REVIEW_ACTION_LIST_ATTEMPT: null,
	GET_ORDER_REVIEW_ACTION_LIST_SUCCESS: null,

	GET_CHAT_LIST_ATTEMPT: null,
	GET_CHAT_LIST_SUCCESS: null,

	SHOW_CHAT_DETAILS_MODAL: null,
	HIDE_CHAT_DETAILS_MODAL: null,

	GET_CHAT_DETAILS_ATTEMPT: null,
	GET_CHAT_DETAILS_SUCCESS: null,

	SEARCH_CHAT_ID_ATTEMPT: null,
	SEARCH_CHAT_ID_SUCCESS: null,

	GET_CLIENT_REVIEW_ACTION_LIST_ATTEMPT: null,
	GET_CLIENT_REVIEW_ACTION_LIST_SUCCESS: null,

	GET_QMSTATS_ATTEMPT: null,
	GET_QMSTATS_SUCCESS: null,

	GET_CEOSTATS_ATTEMPT: null,
	GET_CEOSTATS_SUCCESS: null,

	LOAD_ACTIVE_INACTIVE_LIST_ATTEMPT: null,
	LOAD_ACTIVE_INACTIVE_LIST_SUCCESS: null,

	SHOW_VIOLATION_MODAL: null,
	HIDE_VIOLATION_MODAL: null,

	CREATE_VIOLATION_ATTEMPT: null,
	CREATE_VIOLATION_SUCCESS: null,

	GET_SUPPORT_RULE_LIST_ATTEMPT: null,
	GET_SUPPORT_RULE_LIST_SUCCESS: null,

	SHOW_FINE_SUPPORT_MODAL: null,
	HIDE_FINE_SUPPORT_MODAL: null,

	GET_VIOLATION_LIST_ATTEMPT: null,
	GET_VIOLATION_LIST_SUCCESS: null,

	DELETE_VIOLATION_ATTEMPT: null,
	DELETE_VIOLATION_SUCCESS: null,

	UPDATE_CHAT_STATUS_ATTEMPT: null,
	UPDATE_CHAT_STATUS_SUCCESS: null,

	GET_PHONE_CALL_LIST_ATTEMPT: null,
	GET_PHONE_CALL_LIST_SUCCESS: null,

	UPDATE_PHONE_CALL_ATTEMPT: null,
	UPDATE_PHONE_CALL_SUCCESS: null,

	UPDATE_VIOLATION_ATTEMPT: null,
	UPDATE_VIOLATION_SUCCESS: null,

	DELETE_VIOLATION_ATTEMPT: null,
	DELETE_VIOLATION_SUCCESS: null,

	UPDATE_CLIENT_ATTEMPT: null,

	UPDATE_USER_RISK_LEVEL: null,

	DELETE_STATUS_TOGGLE: null,

	DELETE_OR_RESTORE_ORDER_ATTEMPT: null,
	DELETE_OR_RESTORE_ORDER_SUCCESS: null,


	REVIEWS_LOAD_ATTEMPT: null,
	REVIEWS_LOADED: null,
	REVIEW_LOAD_ATTEMPT: null,
	REVIEW_LOAD_SUCCESS: null,
	ADD_FILTER_REVIEW: null,
	UPDATE_FILTER_REVIEW: null,
	REMOVE_FILTER_REVIEW: null,
	UPDATE_SORTING_REVIEW: null,
	LOAD_UNUSUAL_USERS_LIST_ATTEMPT: null,
	UNUSUAL_USERS_LIST_LOADED: null,
	CLEAR_UNUSUAL_USERS_FILTER: null,

	VIOLATION_FILTER_CHANGED: null,

	ORDER_MESSAGES_LOAD_ATTEMPT: null,
	ORDER_MESSAGES_LOAD_SUCCESS: null,

	ORDER_FILES_LOAD_ATTEMPT: null,
	ORDER_FILES_LOAD_SUCCESS: null,

	GET_LOGS_LIST_ATTEMPT: null,
	GET_LOGS_LIST_SUCCESS: null,

	ADD_FILTER_FOR_ACTION: null,
	UPDATE_LOG_FILTER: null,
	REMOVE_LOG_FILTER: null,
	LOG_FILTERS_CLEAR: null,

	SHOW_CREDIT_MODAL: null,
	HIDE_CREDIT_MODAL: null,

	GET_CLIENT_TRANSACTION_ATTEMPT: null,
	GET_CLIENT_TRANSACTION_SUCCESS: null,

	APPLY_CREDIT_ATTEMPT: null,
	APPLY_CREDIT_SUCCESS: null,

	HIDE_CANCELLATION_MODAL: null,
	SHOW_CANCELLATION_MODAL: null,
	SAVE_CANCELLATION_REQUEST: null,
	CANCELLATION_REQUEST_SAVED: null,
	CANCELLATION_REQUEST_WAS_DELETED: null,
	CANCELLATION_REQUEST_RESOLVE: null,
	CANCELLATION_REQUEST_UNRESOLVE: null,
	CANCELLATION_REQUEST_DELETE: null,
	CANCELLATION_REQUESTS_LIST_LOADED: null,
	LOAD_CANCELLATION_REQUESTS_LIST_ATTEMPT: null,
	CLEAR_CANCELLATION_REQUESTS_FILTER: null,

	LOAD_WM_LIST_ATTEMPT: null,
	WM_LIST_LOADED: null,

	LANDINGS_LOADED: null,
	POSTS_LOADED: null,
	CATEGORIES_LOADED: null,
	APP_ID_LOAD_ATTEMPT: null,

	LANDINGS_LOAD_ATTEMPT : null,
	LANDINGS_LOAD_SUCCESS : null,
	POSTS_LOAD_ATTEMPT: null,
	CATEGORIES_LOAD_ATTEMPT: null,

	LOAD_SPECIFIC_LANDING_ATTEMPT: null,
	LOAD_SPECIFIC_LANDING_SUCCESS: null,

	LOAD_SPECIFIC_POST_ATTEMPT: null,
	LOAD_SPECIFIC_POST_SUCCESS: null,

	SEO_LANDINGS_LOAD_SUCCESS: null,
	DELETE_OR_RESTORE_LANDING_SUCCESS: null,
	LOAD_MY_LANDINGS: null,
	LANDINGS_LOAD_ATTEMPT : null,
	LANDINGS_LOAD_SUCCESS : null,
	UPDATE_LANDINGS_SORTING : null,

	POSTS_LOAD_ATTEMPT: null,

	UPDATE_POST_ATTEMPT:null,
	UPDATE_POST_SUCCESS:null,

	LOAD_SPECIFIC_LANDING_ATTEMPT: null,
	LOAD_SPECIFIC_LANDING_SUCCESS: null,

	LOAD_MORE_CONTENT_FIELD_ATTEMPT: null,

	CREATE_NEW_LANDING_ATTEMPT: null,

	CREATE_NEW_POST: null,
	CREATE_NEW_CATEGORY: null,

	CREATE_NEW_LANDING_SUCCESS: null,

	DELETE_LANDING_ATTEMPT:null,

	DELETE_LANDING_SUCCESS:null,

	CHANGE_DELETE_LANDING_STATE_ATTEMPT:null,
	UPDATE_LANDING_ATTEMPT:null,
	UPDATE_LANDING_SUCCESS:null,
	CHANGE_UPDATE_LANDING_STATE_ATTEMPT:null,


	GET_TASK_LIST_ATTEMPT: null,
	GET_TASK_LIST_SUCCESS: null,

	GET_VIOLATION_STATS_LIST_ATTEMPT:null,
	GET_VIOLATION_STATS_LIST_SUCCESS:null,

	WM_DETAILS_LOADED: null,
	LOAD_WM_DETAILS_ATTEMPT: null,

	WM_INFO_UPDATE_ATTEMPT: null,
	WM_INFO_UPDATE_SUCCESS: null,

	'DELETE_WM_NICKNAME_ATTEMPT': null,
	'DELETE_WM_NICKNAME_SUCCESS': null,

	LOAD_WM_STATS_ATTEMPT: null,
	WM_STATS_LOADED: null,

	CLEAR_WM_LIST_FILTERS: null,
	SET_WM_PROCESSING_STATUS_ATTEMPT: null,
	SET_WM_PROCESSING_STATUS_SUCCESS: null,

	UPDATE_TASK_STATUS_ATTEMPT: null,
	UPDATE_TASK_STATUS_SUCCESS: null,

	GET_TASK_FILTERS_ATTEMPT: null,
	GET_TASK_FILTERS_SUCCESS: null,

	APPLY_TASK_FILTER_PRESET: null,

	MESSAGE_ACCEPT:null,
	MESSAGE_ACCEPTED:null,

	MESSAGE_DELETED:null,

	DISCOUNT_APPLY_ATTEMPT: null,
	DISCOUNT_APPLY_SUCCESS: null,
	SHOW_DISCOUNT_MODAL: null,
	HIDE_DISCOUNT_MODAL: null,

	UPDATE_WM_PULISHED_ATTEMPT: null,
	UPDATE_WM_PULISHED_SUCCESS: null,

	CHANGE_IMPROVEMENT_STATUS_ATTEMPT: null,
	CHANGE_IMPROVEMENT_STATUS_SUCCESS: null,

	LOAD_ALL_IMPROVEMENT_STATUSES_ATTEMPT: null,
	LOAD_ALL_IMPROVEMENT_STATUSES_SUCCESS: null,

	GET_WRITER_RATING_FACTORS_ATTEMPT: null,
	GET_WRITER_RATING_FACTORS_SUCCESS: null,

	CREATE_TASK_ATTEMPT: null,
	CREATE_TASK_SUCCESS: null,

	UPDATE_TASK_ATTEMPT: null,
	UPDATE_TASK_SUCCESS: null,

	REMOVE_TASK_ATTEMPT: null,
	REMOVE_TASK_SUCCESS: null,

	SHOW_TASK_MODAL: null,
	HIDE_TASK_MODAL: null,

	GET_TICKETS_ATTEMPT: null,
	GET_TICKETS_SUCCESS: null,

	GET_TICKET_ATTEMPT: null,
	GET_TICKET_SUCCESS: null,

	UPDATE_TICKET_MESSAGE: null,
	SEND_MESSAGE_FOR_TICKET: null,

	LOAD_AFFILIATE_REMINDERS_ATTEMPT: null,
	LOAD_AFFILIATE_REMINDERS_SUCCESS: null,

	REMINDER_AFFILIATE_LIST_UPDATE: null,
	REMINDER_AFFILIATE_ADD_ATTEMPT: null,
	REMINDER_AFFILIATE_ADD_SUCCESS: null,
	REMINDER_AFFILIATE_UPDATE_ATTEMPT: null,
	REMINDER_AFFILIATE_DELETE_ATTEMPT: null,

	AFFILIATE_LIST_LOAD_ATTEMPT: null,
	AFFILIATE_LIST_LOAD_SUCCESS: null,

	REFRESH_WM_ATTEMPT: null,

	GET_SHIFT_STATS_LIST_ATTEMPT: null,
	GET_SHIFT_STATS_LIST_SUCCESS: null,

	GET_ORDER_APPLICANTS_ATTEMPT: null,
	GET_ORDER_APPLICANTS_SUCCESS: null,

	WRITER_ASSIGN_SUCCESS: null,

	GET_ORDER_CLIENT_NOTES_ATTEMPT: null,
	GET_ORDER_CLIENT_NOTES_SUCCESS: null,

	GET_ORDER_PAYMENTS_ATTEMPT: null,
	GET_ORDER_PAYMENTS_SUCCESS: null,

	ORDER_LOAD_REMINDERS_ATTEMPT: null,
	ORDER_LOAD_REMINDERS_SUCCESS: null,

	REVIEW_BIG_ORDERS_FILTER_CHANGED: null,

	SKILL_LIST_ATTEMPT: null,
	SKILL_LIST_LOADED: null,

	GET_ESSAY_PAGES_LIST_ATTEMPT: null,
	GET_ESSAY_PAGES_LIST_SUCCESS: null,

	OPEN_ESSAY_PAGE_MODAL: null,
	CLOSE_ESSAY_PAGE_MODAL: null,

	CREATE_ESSAY_PAGE_ATTEMPT: null,
	CREATE_ESSAY_PAGE_SUCCESS: null,

	UPDATE_ESSAY_PAGE_ATTEMPT: null,
	UPDATE_ESSAY_PAGE_SUCCESS: null,

	DELETE_ESSAY_PAGE: null,

	OPEN_CONTENT_MODAL: null,
	CLOSE_CONTENT_MODAL: null,

	OPEN_CATEGORIES_MODAL: null,
	CLOSE_CATEGORIES_MODAL: null,

	UPDATE_ESSAY_CATEGORY_ATTEMPT: null,
	UPDATE_ESSAY_CATEGORY_SUCCESS: null,
	DELETE_ESSAY_CATEGORY: null,

	SEARCH_USERS_ON_CSV_FILES: null,
	DOWNLOAD_USERS_ON_CSV_FILES: null,

	GET_DISCOUNT_STATS_ATTEMPT: null,
	GET_DISCOUNT_STATS_SUCCESS: null,

	GET_ORDER_EMAILS_ATTEMPT: null,
	GET_ORDER_EMAILS_SUCCESS: null,

	SET_NOTIFICATION_FILTERS: null,
	UPDATE_NOTIFICATION_SORTING: null,

	LOAD_WRITER_PAYMENTS_ATTEMPT: null,
	LOAD_WRITER_PAYMENTS_SUCCESS: null,

	CLIENT_LOAD_ATTEMPT: null,
	CLIENT_LOAD_SUCCESS: null,

	WRITER_LOAD_ATTEMPT: null,
	WRITER_LOAD_SUCCESS: null,

	GET_VISIT_STATS_ATTEMPT: null,
	GET_VISIT_STATS_SUCCESS: null,

	HIDE_STAT_GRAPH_MODAL: null,
	SHOW_STAT_GRAPH_MODAL: null,

	GET_KPI_SUPPORT_STATS_ATTEMPT: null,
	GET_KPI_SUPPORT_STATS_SUCCESS: null,

	GET_SUPPORT_STATS_ATTEMPT: null,
	GET_SUPPORT_STATS_SUCCESS: null,

	GET_SUPPORT_KPI_ATTEMPT: null,
	GET_SUPPORT_KPI_SUCCESS: null,

	DELETE_REVIEW_ACTION: null,
	REVIEW_ACTION_DELETED: null,

});
